name: angular_compiler
author: Dart Team <misc@dartlang.org>
homepage: https://angulardart.dev/
repository: https://github.com/dart-lang/angular
description: Compiler for AngularDart.
version: 0.4.5

environment:
  sdk: ">=2.5.0-dev.1.0 <3.0.0"

dependencies:
  analyzer: ^0.38.3
  args: ^1.3.0
  build: '>=1.1.0 <2.0.0'
  code_builder: ^3.0.1
  collection: ^1.14.5
  dart_style: ^1.0.9
  logging: '>=0.9.0 <0.12.0'
  meta: ^1.1.4
  path: ^1.6.1
  source_gen: ">=0.9.1 <0.10.0"
  source_span: ^1.4.0
  stack_trace: ^1.9.1

dev_dependencies:
  # This is here in order for it to be resolvable by the analyzer.
  # It is overrode in `dependency_overrides`.
  angular:
  build_runner: ^1.0.0
  build_test: ^0.10.2+5
  test: ^1.3.0

# === vvv REMOVE WHEN PUBLISHING vvv ===
dependency_overrides:
  angular:
    path: ../angular
  angular_ast:
    path: ../angular_ast
# === ^^^ REMOVE WHEN PUBLISHING ^^^ ===
