name: angular_compiler
author: Dart Team <misc@dartlang.org>
homepage: https://github.com/dart-lang/angular
description: Compiler for AngularDart.
version: 0.4.0-alpha+10

environment:
  sdk: ">=2.0.0-dev.46.0 <2.0.0"

dependencies:
  analyzer: ^0.31.0+1
  args: ^1.3.0
  build: ^0.12.0+2
  code_builder: ^3.0.1
  collection: ^1.8.0
  dart_style: ^1.0.9
  logging: '>=0.9.0 <0.12.0'
  meta: ^1.1.2
  path: ^1.5.1
  source_gen: ^0.8.0
  source_span: ^1.4.0
  stack_trace: ^1.9.1

dev_dependencies:
  # This is here in order for it to be resolvable by the analyzer.
  # It is overrode in `dependency_overrides`.
  angular:
  build_runner: ^0.8.0
  build_test: ^0.10.2+1
  test: ^0.12.32

# === vvv REMOVE WHEN PUBLISHING vvv ===
dependency_overrides:
  angular:
    path: ../angular
  angular_ast:
    path: ../angular_ast
# === ^^^ REMOVE WHEN PUBLISHING ^^^ ===
