name: angular_compiler
author: Dart Team <misc@dartlang.org>
homepage: https://github.com/dart-lang/angular
description: Compiler for AngularDart.
version: 0.4.0-alpha+4

environment:
  sdk: '>=2.0.0-dev.3.0 <2.0.0'

dependencies:
  analyzer: '^0.31.0'
  args: '>=0.13.6 <2.0.0'
  build: '>=0.10.0 <0.13.0'
  code_builder: '^3.0.0'
  collection: ^1.8.0
  logging: '>=0.9.0 <0.12.0'
  meta: ^1.0.3
  path: ^1.0.0
  source_gen: '^0.7.4+2'

dev_dependencies:
  # This is here in order for it to be resolvable by the analyzer.
  angular: '^5.0.0-alpha'
  build_test: ^0.9.0
  test: '^0.12.0'

# === vvv REMOVE WHEN PUBLISHING vvv ===
dependency_overrides:
  angular:
    path: ../angular
  angular_ast:
      path: ../angular_ast
# === ^^^ REMOVE WHEN PUBLISHING ^^^ ===
