name: angular_compiler
author: Dart Team <misc@dartlang.org>
homepage: https://github.com/dart-lang/angular
description: Compiler for AngularDart.
version: 0.4.0-alpha+1

environment:
  sdk: '>=1.22.0 <2.0.0'

dependencies:
  analyzer: '^0.31.0-alpha.1'
  args: '>=0.13.6 <2.0.0'
  barback: ^0.15.2+2
  build: ^0.10.0
  collection: ^1.8.0
  glob: ^1.0.0
  logging: '>=0.9.0 <0.12.0'
  meta: ^1.0.3
  path: ^1.0.0
  source_gen: '^0.7.0'

dev_dependencies:
  # This is here in order for it to be resolvable by the analyzer.
  angular: '^4.0.0-alpha'
  build_test: ^0.7.0
  test: '^0.12.0'

# === vvv REMOVE WHEN PUBLISHING vvv ===
dependency_overrides:
  analyzer: '^0.31.0-alpha.1'
  angular:
    path: ../angular
# === ^^^ REMOVE WHEN PUBLISHING ^^^ ===
