name: angular_compiler
repository: https://github.com/dart-lang/angular
description: Compiler for AngularDart.
version: 1.0.1

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  analyzer: ^2.0.0
  args: ^2.0.0
  build: ^2.0.0
  code_builder: ^4.0.0
  collection: ^1.15.0-nullsafety.4
  dart_style: ^2.0.0
  logging: ^1.0.0
  meta: ^1.1.4
  path: ^1.6.1
  package_config: ^2.0.0
  source_gen: ^1.0.0
  source_span: ^1.4.0
  stack_trace: ^1.9.1

dev_dependencies:
  # This is here in order for it to be resolvable by the analyzer.
  # It is overrode in `dependency_overrides`.
  angular:
  build_runner: ^2.0.0
  build_test: ^2.0.0
  mockito: ^5.0.7
  pedantic: ^1.0.0
  test: ^1.3.0

# === vvv REMOVE WHEN PUBLISHING vvv ===
dependency_overrides:
  angular:
    path: ../angular
  angular_ast:
    path: ../angular_ast
# === ^^^ REMOVE WHEN PUBLISHING ^^^ ===
