name: angular_forms
author: Dart Team <misc@dartlang.org>
homepage: https://github.com/dart-lang/angular
description: Forms framework for AngularDart.
version: 1.0.1-alpha+4

environment:
  sdk: '>=2.0.0-dev.3.0 <2.0.0'

dependencies:
  angular: '^5.0.0-alpha+4'
  meta: ^1.1.2

# === vvv REMOVE WHEN PUBLISHING vvv ===
dependency_overrides:
  angular:
    path: ../angular
  angular_ast:
    path: ../angular_ast
  angular_compiler:
    path: ../angular_compiler
# === ^^^ REMOVE WHEN PUBLISHING ^^^ ===
