name: examples.github_issues

environment:
  sdk: ">=2.1.0-dev.5.0 <3.0.0"

dependencies:
  angular_components: ^0.9.0-beta+2
  # No strict dependencies, we always use dependency_overrides.
  angular:
  angular_forms:
  markdown: ^2.0.1
  sass_builder: ^2.0.0

dev_dependencies:
  # No strict dependencies, we always use dependency_overrides.
  angular_test:
  build_runner: ^1.0.0
  build_test: ^0.10.2+5
  build_web_compilers: ^1.0.0
  mockito: ^3.0.0
  test: ^1.3.0

# DO NOT REMOVE. We don't publish this package, it is just for testing.
dependency_overrides:
  angular:
    path: ../../angular
  angular_ast:
    path: ../../angular_ast
  angular_compiler:
    path: ../../angular_compiler
  angular_forms:
    path: ../../angular_forms
  angular_test:
    path: ../../angular_test
