name: angular_ast
author: Dart Team <misc@dartlang.org>
homepage: https://github.com/dart-lang/angular
description: Parser and utilities for AngularDart templates
version: 0.5.0

environment:
  sdk: ">=2.0.0-dev.32.0 <2.0.0"

dependencies:
  analyzer: ^0.31.0+1
  charcode: ^1.1.0
  collection: ^1.14.5
  string_scanner: ^1.0.1
  meta: ^1.1.2
  quiver: ^0.29.0+1
  source_span: ^1.4.0

dev_dependencies:
  build_runner: ^0.8.0
  build_test: ^0.10.1+1
  path: ^1.5.1
  test: ^0.12.32
