name: angular_ast
author: Dart Team <misc@dartlang.org>
homepage: https://github.com/dart-lang/angular
description: Parser and utilities for AngularDart templates
version: 0.4.2

environment:
  sdk: '>=2.0.0-dev.20.0 <2.0.0'

dependencies:
  analyzer: ^0.31.0+1
  charcode: ^1.1.0
  collection: ^1.14.5
  string_scanner: ^1.0.1
  meta: ^1.1.2
  quiver: '>=0.22.0 <0.29.0'
  source_span: ^1.4.0

dev_dependencies:
  path: ^1.5.1
  test: ^0.12.30+1