name: angular_analyzer_plugin
version: 1.0.0-dev
description: Dart analyzer plugin for Angular
homepage: https://angulardart.dev/
repository: https://github.com/dart-lang/angular
environment:
  sdk: ">=2.8.1 <3.0.0"
dependencies:
  analyzer: '>=0.39.8 <0.39.15'
  plugin: ^0.2.0
  analyzer_plugin: '>=0.1.0 <0.3.0'
  angular_ast: ^0.6.0
  meta: ^1.1.4
  yaml: ^2.1.2
  crypto: '>=1.1.1 <3.0.0'
dev_dependencies:
  test_reflective_loader: ^0.1.0
  test: ^1.2.0
  matcher: ^0.12.9
  mockito: ^3.0.0

# === vvv REMOVE WHEN PUBLISHING vvv ===
dependency_overrides:
  angular_ast:
      path: ../angular_ast
# === ^^^ REMOVE WHEN PUBLISHING ^^^ ===
