name: angular2
version: 2.0.0-beta.20
author: Angular Dart Team <angular2@dartlang.org>
description: Framework for modern web applications
homepage: 'https://github.com/dart-lang/angular2'
environment:
  sdk: '>=1.10.0 <2.0.0'
dependencies:
  analyzer: '>=0.24.4 <0.28.0'
  barback: ^0.15.2+2
  build: ^0.3.0
  dart_style: '>=0.1.8 <0.3.0'
  glob: ^1.0.0
  html: ^0.12.0
  intl: ^0.13.0
  logging: '>=0.9.0 <0.12.0'
  observe: ^0.13.1
  path: ^1.0.0
  protobuf: ^0.5.1
  source_span: ^1.0.0
  stack_trace: ^1.6.5
  js: ^0.6.0
dev_dependencies:
  mockito: '>=0.11.0'
  quiver: ^0.21.4
  test: ^0.12.6
  transformer_test: ^0.2.0
transformers:
  - angular2/transform/codegen
  - $dart2js:
      commandLineOptions:
        - '--show-package-warnings'
