name: angular_test
author: Dart Team <misc@dartlang.org>
homepage: https://github.com/dart-lang/angular
description: Testing runner and library for AngularDart
version: 2.3.0

environment:
  sdk: ">=2.2.1-dev.3.0 <3.0.0"

dependencies:
  angular: ^5.3.0
  collection: ^1.14.10
  meta: ^1.1.4
  pedantic: ^1.2.0

dev_dependencies:
  build_runner: ^1.0.0
  build_test: ^0.10.2+5
  build_web_compilers: ^1.0.0
  test: ^1.3.0

# === vvv REMOVE WHEN PUBLISHING vvv ===
dependency_overrides:
  angular:
    path: ../angular
  angular_ast:
    path: ../angular_ast
  angular_compiler:
    path: ../angular_compiler
# === ^^^ REMOVE WHEN PUBLISHING ^^^ ===
