name: angular_test
author: Dart Team <misc@dartlang.org>
homepage: https://github.com/dart-lang/angular
description: Testing runner and library for AngularDart
version: 1.0.0-beta+4

environment:
  sdk: '>=1.24.0 <2.0.0'

executables:
  angular_test:

dependencies:
  angular: '^4.0.0-alpha'
  ansicolor: '^0.0.9'
  args: '>=0.13.7 <2.0.0'
  collection: '^1.14.0'
  func: '>=0.1.1 <2.0.0'
  logging: '^0.11.3+1'
  matcher: '^0.12.0+2'
  meta: '^1.0.0'
  pageloader: '^2.2.5'
  path: '^1.4.1'
  stack_trace: ^1.7.0
  test: '^0.12.17'

# === vvv REMOVE WHEN PUBLISHING vvv ===
dependency_overrides:
  angular:
    path: ../angular
  angular_compiler:
    path: ../angular_compiler
# === ^^^ REMOVE WHEN PUBLISHING ^^^ ===

transformers:
  - angular:
      entry_points: test/**_test.dart
      $exclude:
          - test/**.template.dart

  # Allow test to proxy-load files so we can run AoT tests w/ pub serve.
  - test/pub_serve:
      $include: test/**_test.dart
