name: angular_test
author: Dart Team <misc@dartlang.org>
homepage: https://github.com/dart-lang/angular
description: Testing runner and library for AngularDart
version: 2.0.0-alpha

environment:
  sdk: '>=2.0.0-dev.3.0 <2.0.0'

executables:
  angular_test:

dependencies:
  angular: '^5.0.0-alpha+2'
  ansicolor: '^0.0.9'
  args: '^0.13.7'
  collection: '^1.14.0'
  logging: '^0.11.3+1'
  matcher: '^0.12.0+2'
  meta: '^1.0.0'
  pageloader: '^2.2.5'
  path: '^1.4.1'
  stack_trace: ^1.7.0
  test: '^0.12.17'

dev_dependencies:
  build_web_compilers: ^0.1.1
  build_runner: ^0.7.0
  build_test: ^0.9.0

# === vvv REMOVE WHEN PUBLISHING vvv ===
dependency_overrides:
  analyzer: '^0.31.0-alpha.1'
  angular:
    path: ../angular
  angular_ast:
    path: ../angular_ast
  angular_compiler:
    path: ../angular_compiler
# === ^^^ REMOVE WHEN PUBLISHING ^^^ ===
