name: angular_test
author: Dart Team <misc@dartlang.org>
homepage: https://github.com/dart-lang/angular
description: Testing runner and library for AngularDart
version: 2.0.0-alpha+3

environment:
  sdk: '>=2.0.0-dev.20.0 <2.0.0'

# **DEPRECATED**. Will be removed in a future release.
executables:
  angular_test:

dependencies:
  angular: '^5.0.0-alpha+5'
  matcher: ^0.12.0+2
  meta: ^1.1.2
  test: ^0.12.30+1

dev_dependencies:
  build_runner: ^0.7.9
  build_test: ^0.10.0
  build_web_compilers: ^0.3.0

# === vvv REMOVE WHEN PUBLISHING vvv ===
dependency_overrides:
  angular:
    path: ../angular
  angular_ast:
    path: ../angular_ast
  angular_compiler:
    path: ../angular_compiler
  build_runner:
    git:
      url: https://github.com/dart-lang/build.git
      ref: disable-perf-tracking-in-low-resource-mode
      path: build_runner
# === ^^^ REMOVE WHEN PUBLISHING ^^^ ===
