name: angular_test
repository: https://github.com/angulardart/angular
description: Testing runner and library for AngularDart
version: 3.0.0

environment:
  sdk: '>=2.14.0 <3.0.0'

dependencies:
  angular: ^6.0.0
  collection: ^1.15.0
  meta: ^1.3.0
  pedantic: ^1.10.0

dev_dependencies:
  build_runner: ^2.0.0
  build_test: ^2.0.0
  build_web_compilers: ^3.0.0
  test: ^1.16.0

# === vvv REMOVE WHEN PUBLISHING vvv ===
dependency_overrides:
  angular:
    path: ../angular
  angular_ast:
    path: ../angular_ast
  angular_compiler:
    path: ../angular_compiler
# === ^^^ REMOVE WHEN PUBLISHING ^^^ ===
