# Development tools for working on the AngularDart repository.
name: dev

dependencies:
  args: ^1.4.1
  glob: ^1.1.5
  meta: ^1.1.2
  path: ^1.5.1
  pub_semver: ^1.3.2
  yaml: ^2.1.13

dev_dependencies:
  test: ^0.12.33
  test_descriptor: ^1.0.3

executables:
  pubspec:
  travis:
