# Development tools for working on the AngularDart repository.
name: dev

environment:
  sdk: ">=2.5.0-dev.1.0 <3.0.0"

dependencies:
  args: ^1.4.1
  glob: ^1.1.5
  meta: ^1.1.4
  path: ^1.6.1
  pub_semver: ^1.3.2
  yaml: ^2.1.13

dev_dependencies:
  test: ^1.3.0
  test_descriptor: ^1.0.3

executables:
  pubspec:
  travis:
