name: examples.hello_world

environment:
  sdk: '>=2.14.0 <3.0.0'

dependencies:
  # No strict dependencies, we always use dependency_overrides.
  angular:

dev_dependencies:
  build_runner: ^2.0.0
  build_test: ^2.0.0
  build_web_compilers: ^3.0.0
  pedantic: ^1.0.0

# DO NOT REMOVE. We don't publish this package, it is just for testing.
dependency_overrides:
  angular:
    path: ../../angular
  angular_ast:
    path: ../../angular_ast
  angular_compiler:
    path: ../../angular_compiler
