# #docplaster
name: examples.hello_world

# #docregion env-dev-dep
environment:
  sdk: ">=2.0.0-dev.28.0 <2.0.0"

# #enddocregion env-dev-dep
dependencies:
  angular: ^5.0.0-alpha

# #docregion env-dev-dep
dev_dependencies:
  build_runner: ^0.8.0
  # #enddocregion env-dev-dep
  build_test: ^0.10.1+1
  # #docregion env-dev-dep
  build_web_compilers: ^0.3.4+1
# #enddocregion env-dev-dep

# DO NOT REMOVE. We don't publish this package, it is just for testing.
dependency_overrides:
  angular:
    path: ../../angular
  angular_ast:
    path: ../../angular_ast
  angular_compiler:
    path: ../../angular_compiler
