name: angular_router
author: Dart Team <misc@dartlang.org>
homepage: https://github.com/dart-lang/angular
description: Router for AngularDart.
version: 2.0.0-alpha+3

environment:
  sdk: '>=2.0.0-dev.3.0 <2.0.0'

dependencies:
  angular: '^5.0.0-alpha+3'
  collection: '^1.12.0'
  js: ^0.6.0
  meta: ^1.0.3

dev_dependencies:
  angular_test: ^2.0.0-alpha+1
  build_web_compilers: ^0.1.1
  build_runner: ^0.7.0
  build_test: ^0.9.0
  test: ^0.12.6

# === vvv REMOVE WHEN PUBLISHING vvv ===
dependency_overrides:
  angular:
    path: ../angular
  angular_ast:
    path: ../angular_ast
  angular_compiler:
    path: ../angular_compiler
  angular_forms:
    path: ../angular_forms
  angular_test:
    path: ../angular_test
  angular_router.example:
    path: example
# === ^^^ REMOVE WHEN PUBLISHING ^^^ ===

transformers:
  # Run the code generator on the entire package.
  - angular:
      entry_points: test/**_test.dart
      $exclude:
          - test/url_test.dart
  - test/pub_serve:
      $include: test/**_test.dart
