name: angular_router
author: Dart Team <misc@dartlang.org>
homepage: https://github.com/dart-lang/angular
description: Router for AngularDart.
version: 2.0.0-alpha+5

environment:
  sdk: '>=2.0.0-dev.20.0 <2.0.0'

dependencies:
  angular: '^5.0.0-alpha+5'
  collection: ^1.14.5
  js: ^0.6.0
  meta: ^1.1.2

dev_dependencies:
  async: ^2.0.3
  angular_test: ^2.0.0-alpha+3
  build_web_compilers: ^0.2.1
  build_runner: ^0.7.9
  build_test: ^0.10.0
  test: ^0.12.30+1

# === vvv REMOVE WHEN PUBLISHING vvv ===
dependency_overrides:
  angular:
    path: ../angular
  angular_ast:
    path: ../angular_ast
  angular_compiler:
    path: ../angular_compiler
  angular_test:
    path: ../angular_test
# === ^^^ REMOVE WHEN PUBLISHING ^^^ ===
