name: angular_router
author: Dart Team <misc@dartlang.org>
homepage: https://github.com/dart-lang/angular
description: Router for AngularDart.
version: 2.0.0-alpha+15

environment:
  sdk: ">=2.0.0-dev.64.2 <3.0.0"

dependencies:
  angular: ^5.0.0-beta
  collection: ^1.14.5
  js: ^0.6.0
  meta: ^1.1.2

dev_dependencies:
  async: ^2.0.3
  angular_test: ^2.0.0-beta
  build_runner: ^0.9.0
  build_test: ^0.10.2+5
  build_web_compilers: ^0.4.0+4
  mockito: ^3.0.0-alpha
  test: ">0.12.32+1 <2.0.0"

# === vvv REMOVE WHEN PUBLISHING vvv ===
dependency_overrides:
  angular:
    path: ../angular
  angular_ast:
    path: ../angular_ast
  angular_compiler:
    path: ../angular_compiler
  angular_test:
    path: ../angular_test
# === ^^^ REMOVE WHEN PUBLISHING ^^^ ===
