name: angular
version: 6.0.1-dev
description: Fast and productive web framework
repository: https://github.com/dart-lang/angular
environment:
  sdk: ">=2.8.4 <3.0.0"

dependencies:
  # Runtime (or runtime *and* the compiler).
  collection: ^1.14.5
  intl: ^0.16.0
  js: ^0.6.0
  logging: '>=0.9.0 <0.12.0'
  meta: ^1.1.4
  stack_trace: ^1.9.1

  # Compiler. Eventually we want to move these to angular_compiler.
  analyzer: ^0.40.0

  # It is extremely important these two dependencies stay pinned to current.
  angular_ast: 1.0.0
  angular_compiler: 1.0.0
  ##########################################################################

  build: '>=1.1.0 <2.0.0'
  build_config: '>=0.2.6 <2.0.0' # Runtime dependency with no import
  code_builder: '^3.0.1'
  csslib: ^0.16.0
  path: ^1.6.1
  source_gen: ">=0.9.1 <0.10.0"
  source_span: ^1.4.0

# === vvv REMOVE WHEN PUBLISHING vvv ===
dependency_overrides:
  angular_ast:
      path: ../angular_ast
  angular_compiler:
      path: ../angular_compiler
# === ^^^ REMOVE WHEN PUBLISHING ^^^ ===
