name: angular
version: 5.0.0-alpha+11
author: Dart Team <web@dartlang.org>
description: Fast and productive web framework
homepage: https://webdev.dartlang.org/angular
documentation: https://webdev.dartlang.org/angular/api
environment:
  sdk: ">=2.0.0-dev.46.0 <2.0.0"

dependencies:
  # Runtime (or runtime *and* the compiler).
  collection: ^1.14.5
  intl: '>=0.13.0 <0.16.0'
  js: ^0.6.0
  logging: '>=0.9.0 <0.12.0'
  meta: ^1.1.2
  stack_trace: ^1.9.1

  # Compiler. Eventually we want to move these to angular_compiler.
  analyzer: '^0.31.0+1'
  angular_ast: ^0.5.2
  angular_compiler: ^0.4.0-alpha+11
  build: ^0.12.0+2
  code_builder: '^3.0.1'
  csslib: ^0.14.1
  path: ^1.5.1
  source_gen: ^0.8.0
  source_span: ^1.4.0
  tuple: ^1.0.1

# === vvv REMOVE WHEN PUBLISHING vvv ===
dependency_overrides:
  angular_ast:
      path: ../angular_ast
  angular_compiler:
      path: ../angular_compiler
# === ^^^ REMOVE WHEN PUBLISHING ^^^ ===
