name: angular
version: 7.0.0
description: >-
  Fast and productive web framework by Google.
  Separate, but similar to the JavaScript framework with a similar name.
repository: https://github.com/angulardart/angular
environment:
  sdk: '>=2.14.0 <3.0.0'

dependencies:
  # Runtime (or runtime *and* the compiler).
  built_collection: ^5.0.0
  built_value: ^8.0.0
  collection: ^1.15.0
  intl: ^0.17.0
  js: ^0.6.3
  logging: ^1.0.0
  meta: ^1.3.0
  stack_trace: ^1.10.0
  stream_transform: ^2.0.0

  # Compiler. Eventually we want to move these to angular_compiler.
  analyzer: ^2.0.0

  # It is extremely important these two dependencies stay pinned to current.
  angular_ast: 2.0.0
  angular_compiler: 2.0.0
  ##########################################################################

  build: ^2.0.0
  build_config: ^1.0.0
  code_builder: ^4.0.0
  csslib: ^0.17.0
  path: ^1.8.0
  pedantic: ^1.10.0
  quiver: ^3.0.0
  source_gen: ^1.0.0
  source_span: ^1.8.0

# === vvv REMOVE WHEN PUBLISHING vvv ===
dependency_overrides:
  angular_compiler:
      path: ../angular_compiler
# === ^^^ REMOVE WHEN PUBLISHING ^^^ ===
