name: _goldens.generator
author: Dart Team <web@dartlang.org>
description: Golden file generator for AngularDart.
environment:
  sdk: '>=2.0.0-dev.3.0 <2.0.0'
dev_dependencies:
  angular: '^4.0.0'
  build_runner: ^0.7.4
  build_test: ^0.9.0
  cli_util: ^0.1.0
  mockito: '>=0.11.0 <3.0.0'
  source_span: ^1.4.0
  test: ^0.12.6

# DO NOT REMOVE. We don't publish this package, it is just for testing.
dependency_overrides:
  analyzer: '^0.31.0-alpha.1'
  angular:
    path: ../../angular
  angular_ast:
    path: ../../angular_ast
  angular_compiler:
    path: ../../angular_compiler
  angular_forms:
    path: ../../angular_forms
  angular_router:
    path: ../../angular_router
  angular_test:
    path: ../../angular_test
  build_runner:
    git:
      url: git://github.com/dart-lang/build.git
      ref: 7950a4836e8082609deac91e406d0e5a1b9ddcae
      path: build_runner
