name: examples.registration_form

environment:
  sdk: ">=2.0.0-dev.52.0 <2.0.0"

dependencies:
  angular: ^5.0.0-alpha
  angular_components: ^0.9.0-alpha+6
  angular_forms: ^1.0.1-alpha+6

dev_dependencies:
  build_runner: ^0.8.2
  build_test: ^0.10.1+1
  build_web_compilers: ^0.3.6
  sass_builder: ^1.1.4

# DO NOT REMOVE. We don't publish this package, it is just for testing.
dependency_overrides:
  angular:
    path: ../../angular
  angular_ast:
    path: ../../angular_ast
  angular_compiler:
    path: ../../angular_compiler
  angular_forms:
    path: ../../angular_forms
