name: _benchmarks
author: Dart Team <web@dartlang.org>
description: Benchmarks for AngularDart.
environment:
  sdk: ">=2.5.0-dev.1.0 <3.0.0"

dependencies:
  # No strict dependencies, we always use dependency_overrides.
  angular:

dev_dependencies:
  # No strict dependencies, we always use dependency_overrides.
  angular_test:

  # Actual valid dependencies required.
  build_runner: ^1.0.0
  build_test: ^0.10.2+5
  build_web_compilers: ^2.0.0
  test: ^1.3.0

# DO NOT REMOVE. We don't publish this package, it is just for testing.
dependency_overrides:
  angular:
    path: ../angular
  angular_ast:
    path: ../angular_ast
  angular_compiler:
    path: ../angular_compiler
  angular_test:
    path: ../angular_test
