name: examples.hacker_news_pwa

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  # No strict dependencies, we always use dependency_overrides.
  angular:
  angular_router:
  pwa: ^0.1.10

dev_dependencies:
  # No strict dependencies, we always use dependency_overrides.
  angular_test:
  build_runner: ^0.10.0
  build_test: ^0.10.2+5
  build_web_compilers: ^0.4.0+4
  pageloader: ^3.0.0-beta
  test: ^1.3.0

# DO NOT REMOVE. We don't publish this package, it is just for testing.
dependency_overrides:
  angular:
    path: ../../angular
  angular_ast:
    path: ../../angular_ast
  angular_compiler:
    path: ../../angular_compiler
  angular_router:
    path: ../../angular_router
  angular_test:
    path: ../../angular_test
