name: _goldens
author: Dart Team <web@dartlang.org>
description: Goldens for AngularDart.
environment:
  sdk: ">=2.0.0-dev.28.0 <2.0.0"

dependencies:
  # No strict dependencies, we always use dependency_overrides.
  angular:

dev_dependencies:
  # No strict dependencies, we always use dependency_overrides.
  angular_forms:

  # Actual valid dependencies required.
  build_runner: ^0.7.9
  build_test: ^0.10.0
  dart_style: ^1.0.9
  meta: ^1.1.0
  path: ^1.5.1
  test: ^0.12.32

# DO NOT REMOVE. We don't publish this package, it is just for testing.
dependency_overrides:
  angular:
    path: ../angular
  angular_ast:
    path: ../angular_ast
  angular_compiler:
    path: ../angular_compiler
  angular_forms:
    path: ../angular_forms
